using UnityEditor;
using UnityEngine;
using Blech.World;

namespace Blech.Editor
{
    /// <summary>
    /// Composes biome geometry from primitive Cubes. We use Unity primitives rather than
    /// ProBuilder runtime API so the build is fully reproducible from CLI without ProBuilder
    /// editor-mode dependencies. Materials applied via the M_* assets generated by ShaderBuilder.
    /// </summary>
    public static class BiomeBuilder
    {
        public static Material LoadMat(string name)
        {
            var m = AssetDatabase.LoadAssetAtPath<Material>($"Assets/Blech/Art/Materials/M_{name}.mat");
            if (m == null) Debug.LogWarning($"[Blech] M_{name}.mat not found");
            return m;
        }

        public static GameObject CreateBox(Transform parent, string name, Vector3 pos, Vector3 size, Material mat)
        {
            var go = GameObject.CreatePrimitive(PrimitiveType.Cube);
            go.name = name;
            go.transform.SetParent(parent, false);
            go.transform.localPosition = pos;
            go.transform.localScale = size;
            if (mat != null) go.GetComponent<MeshRenderer>().sharedMaterial = mat;
            return go;
        }

        public static GameObject CreateClimbableBox(Transform parent, string name, Vector3 pos, Vector3 size, Material mat)
        {
            var go = CreateBox(parent, name, pos, size, mat);
            go.AddComponent<ClimbableSurface>();
            return go;
        }

        public static GameObject CreateSlipperyBox(Transform parent, string name, Vector3 pos, Vector3 size, Material mat)
        {
            var go = CreateClimbableBox(parent, name, pos, size, mat);
            go.AddComponent<SlipperySurface>();
            return go;
        }

        public static GameObject CreateCheckpoint(Transform parent, string name, Vector3 pos, string display = "Blechmark")
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);
            go.transform.localPosition = pos;
            var bc = go.AddComponent<BoxCollider>();
            bc.isTrigger = true;
            bc.size = new Vector3(1.5f, 1.5f, 1.5f);
            var cp = go.AddComponent<Checkpoint>();
            cp.displayName = display;
            return go;
        }

        public static GameObject InstantiatePrefab(string path, Transform parent, Vector3 pos)
        {
            var src = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            if (src == null) { Debug.LogWarning($"[Blech] prefab not found: {path}"); return null; }
            var go = (GameObject)PrefabUtility.InstantiatePrefab(src, parent);
            go.transform.localPosition = pos;
            return go;
        }

        // ---------- Biome 1: Intestine ----------
        public static GameObject BuildIntestine(Transform sceneRoot)
        {
            var root = new GameObject("Biome_1_Intestine");
            root.transform.SetParent(sceneRoot, false);
            var t = root.transform;
            var mat = LoadMat("Intestine_Organic");

            CreateBox(t, "Floor", new Vector3(0, 0, 0), new Vector3(6, 0.5f, 10), mat);
            CreateBox(t, "WallL", new Vector3(-3, 2, 0), new Vector3(0.5f, 4, 10), mat);
            CreateBox(t, "WallR", new Vector3(3, 2, 0), new Vector3(0.5f, 4, 10), mat);
            CreateClimbableBox(t, "ClimbWall", new Vector3(0, 3, 8), new Vector3(6, 6, 0.5f), mat);
            CreateSlipperyBox(t, "MucusPatch", new Vector3(0, 4, 7.85f), new Vector3(4, 1, 0.2f), LoadMat("Mucus_Slip"));
            CreateBox(t, "TopLedge", new Vector3(0, 6.5f, 9), new Vector3(4, 0.5f, 4), mat);
            CreateCheckpoint(t, "CP_Start", new Vector3(0, 0.6f, 1));
            CreateCheckpoint(t, "CP_IntestineTop", new Vector3(0, 7, 9));
            return root;
        }

        // ---------- Biome 2: Stomach ----------
        public static GameObject BuildStomach(Transform sceneRoot)
        {
            var root = new GameObject("Biome_2_Stomach");
            root.transform.SetParent(sceneRoot, false);
            root.transform.localPosition = new Vector3(0, 0, 25);
            var t = root.transform;
            var wall = LoadMat("Stomach_Wall");

            CreateBox(t, "Floor", new Vector3(0, 0.5f, 0), new Vector3(20, 1, 20), wall);
            CreateBox(t, "WallN", new Vector3(0, 8, 10), new Vector3(20, 16, 1), wall);
            CreateBox(t, "WallS", new Vector3(0, 8, -10), new Vector3(20, 16, 1), wall);
            CreateBox(t, "WallE", new Vector3(10, 8, 0), new Vector3(1, 16, 20), wall);
            CreateBox(t, "WallW", new Vector3(-10, 8, 0), new Vector3(1, 16, 20), wall);

            InstantiatePrefab("Assets/Blech/Prefabs/Hazards/AcidPool.prefab", t, new Vector3(0, 1.5f, 0));

            CreateBox(t, "Plat_A", new Vector3(-4, 3, -3), new Vector3(2, 0.3f, 2), wall);
            CreateBox(t, "Plat_B", new Vector3(3, 5, 0), new Vector3(2, 0.3f, 2), wall);
            CreateBox(t, "Plat_C", new Vector3(-3, 7, 3), new Vector3(2, 0.3f, 2), wall);
            CreateBox(t, "Plat_D", new Vector3(4, 9, 1), new Vector3(2, 0.3f, 2), wall);

            CreateClimbableBox(t, "ClimbPatch_1", new Vector3(0, 7, 9.5f), new Vector3(3, 5, 0.3f), wall);

            var geyser = InstantiatePrefab("Assets/Blech/Prefabs/Hazards/AcidGeyser.prefab", t, new Vector3(0, 1.5f, 0));
            if (geyser != null) geyser.transform.localScale = new Vector3(1, 1.2f, 1);

            CreateCheckpoint(t, "CP_StomachTop", new Vector3(4, 10, 1));
            CreateClimbableBox(t, "ExitClimb", new Vector3(0, 10, 9.7f), new Vector3(3, 12, 0.3f), wall);
            return root;
        }

        // ---------- Biome 3: Throat ----------
        public static GameObject BuildThroat(Transform sceneRoot)
        {
            var root = new GameObject("Biome_3_Throat");
            root.transform.SetParent(sceneRoot, false);
            root.transform.localPosition = new Vector3(0, 22, 30);
            var t = root.transform;
            var mat = LoadMat("Throat_Tissue");

            CreateClimbableBox(t, "WallN", new Vector3(0, 15, 2), new Vector3(4, 30, 0.5f), mat);
            CreateClimbableBox(t, "WallS", new Vector3(0, 15, -2), new Vector3(4, 30, 0.5f), mat);
            CreateClimbableBox(t, "WallE", new Vector3(2, 15, 0), new Vector3(0.5f, 30, 4), mat);
            CreateClimbableBox(t, "WallW", new Vector3(-2, 15, 0), new Vector3(0.5f, 30, 4), mat);

            CreateBox(t, "Ledge1", new Vector3(0, 8, 1.5f), new Vector3(1.5f, 0.3f, 1.5f), mat);
            CreateBox(t, "Ledge2", new Vector3(1.5f, 14, 0), new Vector3(1.5f, 0.3f, 1.5f), mat);
            CreateBox(t, "Ledge3", new Vector3(0, 20, -1.5f), new Vector3(1.5f, 0.3f, 1.5f), mat);
            CreateBox(t, "Ledge4", new Vector3(-1.5f, 26, 0), new Vector3(1.5f, 0.3f, 1.5f), mat);

            CreateSlipperyBox(t, "Drip1", new Vector3(0, 12, 1.8f), new Vector3(0.5f, 5, 0.2f), LoadMat("Mucus_Slip"));
            CreateSlipperyBox(t, "Drip2", new Vector3(0, 22, -1.8f), new Vector3(0.5f, 5, 0.2f), LoadMat("Mucus_Slip"));

            var mid = InstantiatePrefab("Assets/Blech/Prefabs/Hazards/WindHazard.prefab", t, new Vector3(0, 15, 0));
            if (mid != null)
            {
                var w = mid.GetComponent<WindHazard>();
                if (w != null) { w.gustDirection = Vector3.right; w.gustStrength = 4f; }
            }
            var upper = InstantiatePrefab("Assets/Blech/Prefabs/Hazards/WindHazard.prefab", t, new Vector3(0, 25, 0));
            if (upper != null)
            {
                var w = upper.GetComponent<WindHazard>();
                if (w != null) { w.gustDirection = Vector3.up; w.gustStrength = 8f; }
            }

            CreateCheckpoint(t, "CP_ThroatMid", new Vector3(1.5f, 14.5f, 0));
            return root;
        }

        // ---------- Biome 4: Mouth + Finish ----------
        public static GameObject BuildMouth(Transform sceneRoot)
        {
            var root = new GameObject("Biome_4_Mouth");
            root.transform.SetParent(sceneRoot, false);
            root.transform.localPosition = new Vector3(0, 52, 30);
            var t = root.transform;

            CreateBox(t, "Tongue", new Vector3(0, 0, 6), new Vector3(8, 0.5f, 12), LoadMat("Tongue"));
            CreateBox(t, "TeethL", new Vector3(-4.5f, 2, 6), new Vector3(1, 4, 12), MakeTeethMat());
            CreateBox(t, "TeethR", new Vector3( 4.5f, 2, 6), new Vector3(1, 4, 12), MakeTeethMat());
            CreateBox(t, "Sky",    new Vector3(0, 6, 14), new Vector3(30, 20, 0.2f), MakeSkyMat());

            var finishGo = new GameObject("FinishLine");
            finishGo.transform.SetParent(t, false);
            finishGo.transform.localPosition = new Vector3(0, 1, 12);
            var fc = finishGo.AddComponent<BoxCollider>(); fc.isTrigger = true; fc.size = new Vector3(10, 4, 1);
            finishGo.AddComponent<FinishTrigger>();

            var confetti = InstantiatePrefab("Assets/Blech/Prefabs/FX/FX_Confetti.prefab", t, new Vector3(0, 1, 12));
            if (confetti != null) confetti.SetActive(false);

            return root;
        }

        static Material MakeTeethMat()
        {
            const string path = "Assets/Blech/Art/Materials/M_Teeth.mat";
            var m = AssetFactory.CreateOrUpdateMaterial(path, Shader.Find("Universal Render Pipeline/Lit"));
            m.SetColor("_BaseColor", Color.white); m.SetFloat("_Smoothness", 0.8f);
            EditorUtility.SetDirty(m);
            return m;
        }

        static Material MakeSkyMat()
        {
            const string path = "Assets/Blech/Art/Materials/M_Sky.mat";
            var m = AssetFactory.CreateOrUpdateMaterial(path, Shader.Find("Universal Render Pipeline/Unlit"));
            m.SetColor("_BaseColor", new Color(0.4f, 0.78f, 1f));
            EditorUtility.SetDirty(m);
            return m;
        }
    }
}
